export const NEW_EMPLOYEE = 'NEW_EMPLOYEE'
export const CHANGE_EMPLOYEE_FIELD = 'CHANGE_EMPLOYEE_FIELD'
export const CHANGE_EMPLOYEE_PROJECT_FIELD = 'CHANGE_EMPLOYEE_PROJECT_FIELD'
export const MARK_EMPLOYEE_AS_READ = 'MARK_EMPLOYEE_AS_READ'

export const NEW_PROJECT = 'NEW_PROJECT'
export const CHANGE_PROJECT_FIELD = 'CHANGE_PROJECT_FIELD'
export const MARK_PROJECT_AS_READ = 'MARK_PROJECT_AS_READ'

export const ADD_APP_ERROR = 'ADD_APP_ERROR'
export const REMOVE_APP_ERROR = 'REMOVE_APP_ERROR'

export const FETCH_ALL = 'FETCH_ALL'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'
